[build]
  base = "c2"
  command = "npm install && npm run build"
  publish = "c2/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Configuraci√≥n para generar previews de branches (deploy previews)
[context.branch-deploy]
  base = "c2"
  command = "npm install && npm run build"
  publish = "c2/dist"

[context.deploy-preview]
  base = "c2"
  command = "npm install && npm run build"
  publish = "c2/dist"

[context.production]
  base = "c2"
  command = "npm install && npm run build"
  publish = "c2/dist"

